Update patch set 1
Patch Set 1:

the blobs, for example qcom location, looks for msim references and crashes because of this. removing /system/priv-app/com.qualcomm.location/ solves this for me.

so which way to go? waiting for new blobs to come or just removing them until multisim is back?

java.lang.ClassNotFoundException: Didn't find class "android.telephony.MSimTelephonyManager"

Patch-set: 1